language: python

python:
  - "3.6"
  - "3.7"

install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "bdist_wheel"
  on:
    tags: true
  verbose: true
