language: python

python:
  - "3.6"
  - "3.7"

install: pip install tox-travis
script: tox

branches:
  only: 
    - master
    - '/^\d+\.\d+\.\d+$/'  # build tag commits (matches 'x.y.z' tags only)

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "bdist_wheel"
  on:
    tags: true
  skip_existing: true
  verbose: true
